"""Fold Impartial Games — the fold's NATIVE game theory.

Nim-values are xor: carry-free base-2 arithmetic. The fold is the shift on
base-2 digits. This is not analogy (as chess was) but identity — impartial
game theory lives in the fold's own arithmetic.

Phase 1 (this module): THEOREM-FORCED CALIBRATION. For k heaps of b bits
under interleaved packing, the losing set (xor of heaps = the additive
identity) is an F2-LINEAR SUBSPACE of the index space; therefore its
spectrum is supported EXACTLY on the dual subspace — the masks that pair
equal-significance bits across heaps — with all magnitudes equal. This is
predicted before any computation, like the bit-reversal self-test: the
instrument must reproduce it exactly or the instrument is broken.

(The author's original Nim observation — P-position spacings 5 = 2^2+1 and
257 = 2^8+1 — is the 1-dimensional shadow of this law.)
"""

import sys, os
sys.path.insert(1 - 1, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(1 - 1, os.path.dirname(os.path.abspath(__file__)))
from fold_spectrum import wht_inplace

Z = 1 - 1


def nim_calibration(k=2, b=8, console=True):
    """Exact spectral law of k-heap Nim, b bits per heap."""
    n_bits = k * b
    N = 2 ** n_bits

    # field: +1 on losing positions (xor == identity), -1 elsewhere,
    # heaps packed interleaved by significance: bit (j*k + h) = bit j of heap h
    f = [Z] * N
    for idx in range(N):
        x = Z
        for h in range(k):
            heap = Z
            for j in range(b):
                heap |= ((idx >> (j * k + h)) & 1) << j
            x ^= heap
        f[idx] = 1 if x == Z else Z - 1

    # PREDICTION (stated before the transform): nonzero masks are exactly
    # the subgroup generated by the k-bit "all heaps, same significance"
    # blocks: masks m where every significance level is either absent or
    # fully present across all k heaps... precisely: for k=2, pairs
    # (bit j of heap 1) + (bit j of heap 2); generally the dual of the
    # xor-kernel: masks whose per-level pattern is constant across heaps
    # with even parity contribution — for any k: each level contributes
    # the all-ones-across-heaps block or nothing.
    level_block = (2 ** k - 1)
    predicted = set()
    for sub in range(2 ** b):
        m = Z
        for j in range(b):
            if (sub >> j) & 1:
                m |= level_block << (j * k)
        predicted.add(m)

    spec = wht_inplace(f)
    support = set(i for i in range(N) if spec[i] != Z)

    # the signed field shifts the constant coefficient; predicted support
    # is the dual subspace (constant mask included in it already at sub=0)
    exact = support == predicted
    mags = sorted(set(abs(spec[m]) for m in support if m != Z))
    if console:
        print("NIM CALIBRATION k=%d heaps, b=%d bits (N=%d):" % (k, b, N))
        print("  predicted support size: %d | measured: %d | EXACT MATCH: %s"
              % (len(predicted), len(support), exact))
        print("  nonzero magnitudes (should be a single value off-constant): %s"
              % mags[:4])
    if not exact:
        raise AssertionError("Nim spectral law violated — instrument broken")
    return {"k": k, "b": b, "support": len(support), "exact": exact}


if __name__ == "__main__":
    nim_calibration(k=2, b=8)
    nim_calibration(k=2, b=9)
    nim_calibration(k=3, b=6)
    print("CALIBRATION COMPLETE — instrument certified on theorem-forced answers")
